ALTER TABLE "veiculos"
  ADD COLUMN "marca" TEXT,
  ADD COLUMN "modelo" TEXT,
  ADD COLUMN "ano_modelo" INTEGER,
  ADD COLUMN "consumo_gasolina" DOUBLE PRECISION NOT NULL DEFAULT 11,
  ADD COLUMN "consumo_etanol" DOUBLE PRECISION NOT NULL DEFAULT 7.7,
  ADD COLUMN "preco_etanol" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "desgaste_estimado_km" DOUBLE PRECISION NOT NULL DEFAULT 0;
